name: my_environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cmake
  - dlib
  - matplotlib
  - mtcnn
  - opencv-python
  - tensorflow
  - face-recognition
  - face-recognition-models
